#!/bin/bash
# This should go in the "hooks" folder of your bare deployment repo.
# NOTE: You need to update this manually!

TARGET="/srv/discord/ReactionRoleBot"
TEMP="/tmp/discord/ReactionRoleBot.git"
REPO="/srv/discord/ReactionRoleBot.git"
NODE_ENV="prod"

# Download all the dependencies and stuff
mkdir -p $TEMP
git --work-tree=$TEMP --git-dir=$REPO checkout -f
cd $TEMP
npm install
NODE_ENV=$NODE_ENV npm run knex migrate:latest

# Now install the code
cd /
rm -rf $TARGET
mv $TEMP $TARGET

# Restart the app
systemctl restart reactionrolebot.service
